### PR TITLE
Readme.md update

### PR DESCRIPTION
**Pull request by psiphi75**
... more to come.

### CODE REVIEW

**Comment by adityapatadia** [comment]
I tried this long ago. @jadonk is not willing to merge, that's why a fork is created and maintained by me.

**Comment by psiphi75** [comment]
...doh, sent a pull request to the wrong branch.

**Comment by jadonk** [comment]
@adityapatadia I'm willing to merge changes, just not sweeping changes that break things I'm trying to do.

**Comment by psiphi75** [comment]
@jadonk as an active user of octalbonescript I think it would be great to see octalbonescript (OBS) merge back into bonescript.  Although I see that there would breaking changes if the merge were to happen as it is now.  I believe that it would be possible to merge and reduce the number of breaking changes.

The reason I use OBS over bonescript is that it works with more recent kernels and is more intuitive when coming from a node.js background (asynchronicity and standard callbacks) and I have found it to be more stable.

I would be glad to discuss in more detail and help in the merge process (dev/testing).

**Comment by jadonk** [comment]
@psiphi75 that'd be great. I'm happy to comment against a pull request. With the 0.5.x branch of BoneScript, support is now there for the 4.1 kernels. We simplified it to use the pinmux helpers rather than load device tree fragments. Moving forward, I'd like to rely on pinmux helpers and provide ways to help users ensure a suitable pinmux helper is installed for the pins they want to use.

**Comment by psiphi75** [comment]
@adityapatadia: I have added a couple of feature requests to @jadonk for bonescript.  See:
 - https://github.com/jadonk/bonescript/issues/124
 - https://github.com/jadonk/bonescript/issues/125

Let me know if you have any comments.

**Pull request closed without merging**
